{% set name = "igl" %}
{% set version = "2.5.4.dev0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geometryprocessing/libigl-python-bindings/archive/{{ version }}.tar.gz
  sha256: dd417f8c101114f4cb73f7f2c8c0167df081db43b051de4cf2169f1d92f8c964

build:
  number: 0
  script:
    # Azure pipeline failed with this error:
    # ##[warning]Free memory is lower than 5%; Currently used: 95.21%
    # So set number of jobs to 2 instead of default 8 (4 also didn't work):
    # https://github.com/libigl/libigl-python-bindings/blob/2.4.1/setup.py#L57-L60
    # CPU_COUNT holds the number of CPUS we have on each CI.
    - export MAX_JOBS=${CPU_COUNT}                # [unix]
    - set MAX_JOBS=1                              # [win]
    - set "CXX_FLAGS=%CXX_FLAGS% /bigobj /Zm600"  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    # https://github.com/libigl/libigl-python-bindings/blob/main/cmake/Warnings.cmake#L2
    - cmake >=3.5,<4.0
    - make
  host:
    - libblas
    - libcblas
    - nanobind >=1.3.2
    - numpy >=2.0.0
    - packaging
    - pip
    - python
    - scikit-build-core >=0.10
    - scipy
    - typing_extensions
  run:
    - numpy
    - python
    - scipy

test:
  imports:
    - igl

about:
  home: https://libigl.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.TXT
  summary: Simple python geometry processing library
  description: |
    libigl is a simple python and C++ geometry processing library.
    We have a wide functionality including construction of
    sparse discrete differential geometry operators and
    finite-elements matrices such as the cotangent Laplacian and
    diagonalized mass matrix, and
    simple facet and edge-based topology data structures.
  doc_url: https://libigl.github.io/libigl-python-bindings/
  dev_url: https://github.com/libigl/libigl-python-bindings

extra:
  recipe-maintainers:
    - teseoch
    - fwilliams
    - skoch9
    - danielepanozzo
