{% set name = "igl" %}
{% set version = "2.2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geometryprocessing/libigl-python-bindings/archive/{{ version }}.tar.gz
  sha256: 5e430f7c3b082e6d589e5416eb1a295fda21b38c17fe0e7625850f4564213ed4

build:
  number: 0
  skip: true  # [py<31]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - setuptools
    - python
    - pip
    - libblas
    - libcblas
    - make
    - numpy
    - scipy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - igl

about:
  home: https://libigl.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.TXT
  summary: Simple python geometry processing library
  description: |
    libigl is a simple python and C++ geometry processing library.
    We have a wide functionality including construction of
    sparse discrete differential geometry operators and
    finite-elements matrices such as the cotangent Laplacian and
    diagonalized mass matrix, and
    simple facet and edge-based topology data structures.
  doc_url: https://libigl.github.io/libigl-python-bindings/
  dev_url: https://github.com/libigl/libigl-python-bindings

extra:
  recipe-maintainers:
    - teseoch
    - fwilliams
    - skoch9
    - danielepanozzo
