travis:
  secure:
    BINSTAR_TOKEN: daRhpkZWN+S0z/YOYvIiok5eEh/PRU9aHFXQJZxVc87Z+75jzfLO32P15ENspvBX69eGP8rdAuD0vTq1ZIOKSLauoj6FrqJ9luttZmigBBPcdMda7kpGLf9qrF0AeDf2MG+QtpyqAN7IHIRJlama8V8Jt0TdDfiH0jmXZwiZIcYFtEtWzmit1JNdAMjm/yL07Ko6QGXOSoPb3cxz2U3H9kERPzPLdz+YRS+1ZDTIobrq/WSSKPs9EsjXIhl8Q9sSx/7mVzXMbeEgxBB/1ZVnxeciMl7bnQ1Qofr4oS9roLrN5pq7fitio6u+zKOrPkHR/l6gpmL2QQ5oceWBWqnIU4jjWI2N64Ui93mWp3HnhL4cnBatYSUYkJ+tzIftX/ZyYK2P5CZDXP4fswkLWQ8Cx8uja4GxoeV57KQ/X4H7DVKTfPhePTQ1uhiaeN7ESC8OQQZuyIJ+8w00Ahk5SCRAydDc3Hz8xp3xrWhlol4eGwYxVrCefsQLCFur6KzzW/Ez6ii+YhxMtApxE4OxUcuSOhYNHHNzlnCRa1ksl/pWQtx3XQ3oD22YDE+qCwDYoCB9mlksjlEL7oi83IhD60QJ6jsAcWhW//UVdX4GHSVnZPbAWIGqE3riLh8U7u/FqoggKRLVRxMeCgAkXyOTasmqvWhlZMSlITkS17k0MUSkhlM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
